### ISSUE TITLE
Creating a duplicate binding with different types doesn't crash

### ISSUE THREAD

**Issue by mohe2015** [scala-loci/scala-loci#2]
Hi,

when creating multiple `Binding`s registered with the same name it doesn't error. Also this doesn't even error when the types are different which sounds like a weird use case.

**Comment by pweisenburger** [comment]
Thanks for the report. I think just constructing two `Binding` objects with the same name should not throw an error but using them to bind values on the same `Registry` is problematic: So far, binding a new value with the same name just silently re-binds the value (removing the old binding). I suppose this is probably not what is usually intended.

7ede95e changes the behavior such that `bind*` methods of `Registry` throw an error if a value is already bound to the same name. In case you do want to re-bind a value, you now have to explicitly `unbind` the old value before.

This should improve how this situation is handled an error out for improper use.
