### ISSUE TITLE
scalajs-dom and scala-library-sjs dependencies in JVM projects

### ISSUE THREAD

**Issue by rmgk** [scala-loci/scala-loci#9]
A couple of projects:
lociCommunicatorWsWebNative
lociCommunicatorBroadcastChannel
lociCommunicatorWebRtc

Have a dependency to scalajsDom which in turn depends on the scalajs version of the standard library.

This seems to be no problem most of the time, but when trying to export the application to either a set of jar files or to a fat jar, the conflicting library can cause the program to not work at all because the wrong jar is loaded causing a crash with some missing method error.

This is fixable on the user side by not including the dependency or excluding the transitive dependencies, but it is also extremely confusing, because the failure seems to be nondeterministic (maybe depending on the order in which jars are loaded from the file system, which – when passing them via wildcard selection – may actually depend on inode numbers or something similar that is consistent on each machine, but may vary between different machines … (yes, just venting because I got about 3 more grey hairs while trying to figure out why one of my students had this problem 😄))

I think the dependencies are just for the JVM stubs, so maybe they could be labeled as provided/compile internal or however these things are called … ?

**Comment by pweisenburger** [comment]
Making the dependencies for these stubs "compile-internal" seems reasonable. Does 0baa9b4 fix the problem?

**Comment by pweisenburger** [comment]
I changed from "compile-internal" to "provided" (b8a68bf) so that the (compile-time) dependencies are still recorded in the published pom file. That should still address the issue, I hope.
